// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import "../libraries/PlayerLibrary.sol";
import "../items/CAFConsumableItems.sol";

interface ICAFCompanyItems {
    // ========================== ACTIONS ==========================
    /// @notice Replenish the company's energy.
    /// @dev Energy is used to perform actions in the game.
    /// @param _companyId The id of the company
    /// @param _item The consumable item to replenish energy
    /// STORY
    ///   - Players must replenish energy to keep operations running.
    function replenishEnergy(
        uint256 _companyId,
        CAFConsumableItems _item
    ) external;

    // =========================== STATE ===========================
    /// @notice Role of the company in the game.
    /// @dev The role determines the company's abilities and restrictions.
    /// @param _companyId The id of the company
    /// STORY
    ///   - Companies can be:
    ///     - Coffee Company
    ///     - Machine Company
    ///     - Material Company
    function role(
        uint256 _companyId
    ) external view returns (PlayerLibrary.PlayerRole);

    /// @notice The company's energy is used to perform actions in the game.
    /// @dev Energy consumption affects the company's ability to operate.
    /// @param _companyId The id of the company
    /// STORY
    ///   - Each company starts with a maximum of 100 energy.
    ///   - Every day, 10 energy is consumed to maintain production.
    ///   - Players must replenish energy to keep operations running.
    function energy(uint256 _companyId) external view returns (uint8);

    /// @notice The total market capitalization of the company.
    /// @dev Represents the total valuation of the company's assets in the game.
    /// @param _companyId The id of the company
    /// @return The market capitalization of the company
    /// STORY
    ///  - Market capitalization is calculated as the sum of all assets owned by the company.
    function capitalization(uint256 _companyId) external view returns (uint256);

    /// @notice The total revenue generatzd by the company.
    /// @dev This is the accumulated revenue from business activities.
    /// @param _companyId The id of the company
    /// @return The revenue of the company
    /// STORY
    ///   - Revenue is generated by selling products or services.
    function revenue(uint256 _companyId) external view returns (uint256);

    /// @notice The net profit of the company after deducting expenses.
    /// @dev Profit is calculated as revenue minus costs.
    /// @param _companyId The id of the company
    /// @return The profit of the company
    function profit(uint256 _companyId) external view returns (int256);

    /// @notice Check if the company exists
    /// @param _id The id of the company
    /// @return True if the company exists
    function isCompany(uint256 _id) external view returns (bool);

    // ========================== EVENTS ===========================

    /// @notice Emitted when the company consumes energy.
    event EnergyConsumed(uint256 companyId, uint8 amount);

    /// @notice Emitted when the company replenishes energy.
    event EnergyReplenished(uint256 companyId, uint8 amount);

    /// @notice Emitted when the market cap of a company changes.
    event MarketCapUpdated(uint256 companyId, uint256 newMarketCap);

    /// @notice Emitted when the revenue of a company increases.
    event RevenueGenerated(uint256 companyId, uint256 amount);

    /// @notice Emitted when the company's profit is updated.
    event ProfitUpdated(uint256 companyId, int256 newProfit);
}
